#!/usr/bin/busybox ash

gnu_logo() {
    GNU="H4sIAAAAAAAAA21QQW6DMBC8+xVzM5G867tzoeo3LGHapBJSCVJobzy+Y+MAbbNCtjwzOzuLAauT
         lEsc9nICK1ADqOVTBYJlpxc+RYFEhc8Kj2eVKEE0IbNhhTrVDPLsqiZl0oSwaTwpTcFS2kUt45Zd
         Q1PSdHSpNkQobW3JaVLQ1deXmCVl5BHrOM+VYqBF5x+7tSdCPBJShFNr1qDeidi6CPfX6ESTSF65
         /iPr7SpoGoZgnNODgieXk+W82aV5EJf+Nlw/7YzhNnzd+/Fj3nqw+nE/TpZ9OORf7T2wZRIjumML
         2pe3/v17Rvs6jeN0me7XQ8/WBJzDEV8ZW67feGX4/cVLbv8ERjob8wNgCl2LYgIAAA=="

    echo "$GNU" | sed 's/ //g' | base64 -d | gzip -d | cat
}

launch_shell() {
    export PS1='[busybox \W]\$ '
    [ "$1" = "--exec" ] && exec setsid cttyhack ash -i
    setsid cttyhack ash -i
}

cmdline() {
    local value
    value=" $(cat /proc/cmdline) "
    value="${value##* ${1}=}"
    value="${value%% *}"
    [ -n "$value" ] && echo "$value"
}

/usr/bin/busybox --install -s
gnu_logo

mount -t proc     proc /proc -o nosuid,noexec,nodev
mount -t sysfs    sys  /sys  -o nosuid,noexec,nodev
mount -t devtmpfs dev  /dev  -o nosuid,mode=0755
mount -t tmpfs    run  /run  -o nosuid,nodev,mode=0755

cryptdevice_uuid="$(cmdline 'rd.luks.uuid')"
if [ -n "$cryptdevice_uuid" ] ; then
    cryptdevice="$(findfs "UUID=$cryptdevice_uuid")"
    [ -b "$cryptdevice" ] || launch_shell --exec
    mkdir -p /run/cryptsetup

    allowdiscards="$(cmdline 'rd.luks.allow-discards')"
    if [ -n "allowdiscards" ] ; then
        cryptsetup luksOpen --allow-discards "$cryptdevice" "root_crypt" || launch_shell --exec
    else
        cryptsetup luksOpen "$cryptdevice" "root_crypt" || launch_shell --exec
    fi
fi

lvm_vg="$(cmdline 'rd.lvm.vg')"
if [ -n "$lvm_vg" ] ; then
    lvm vgchange -aly "$lvm_vg"
    lvm vgscan --mknodes
fi

resume="$(cmdline 'resume')"
[ -z "$resume" ] || resumedev="$(findfs "$resume")"
if [ -e /sys/power/resume -a -b "$resumedev" ] ; then
    printf "%d:%d" $(stat -Lc "0x%t 0x%T" "$resumedev") > /sys/power/resume
fi

rootdevice_cmd="$(cmdline 'root')"
rootdevice="$(findfs "$rootdevice_cmd")"
[ -b "$rootdevice" -o -h "$rootdevice" ] || launch_shell --exec

fstype="$(cmdline 'rootfstype')"
[ -n "$fstype" ] || fstype="auto"
rflags="$(cmdline 'rootflags')"
[ -n "$rflags" ] || rflags="ro,noatime"
mount -t "$fstype" -o "$rflags" "$rootdevice" /mnt || launch_shell --exec

rdbreak="$(cmdline 'rd.break')"
[ -z "$rdbreak" ] || launch_shell

umount /proc
umount /sys
umount /dev
umount /run

exec switch_root /mnt /sbin/init

# vim: set ft=sh ts=4 sw=4 et:
