---
- name: Symlink für shilunski Logrotate anlegen
  ansible.builtin.file:
    src: /home/daniel/shilunski/shilunski.logrotate
    dest: /etc/logrotate.d/shilunski
    state: link
    owner: root
    group: root
  tags:
    - shilunski_logrotate
