---
- name: .config Verzeichnis anlegen
  ansible.builtin.file:
    path: "{{ item.home }}/.config"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: '0755'
  loop: "{{ common_user_list }}"
  tags:
    - ranger

- name: .bash_aliases für root und den Hauptbenutzer verteilen
  ansible.builtin.copy:
    src: "{{ common_dotfiles_path }}/.bash_aliases"
    dest: "{{ item.home }}/.bash_aliases"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: '0644'
  loop: "{{ common_user_list }}"
  tags:
    - bash

- name: Tmux config verteilen
  ansible.builtin.copy:
    src: "{{ common_dotfiles_path }}/.tmux.conf"
    dest: "{{ item.home }}/.tmux.conf"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: '0644'
  loop: "{{ common_user_list }}"
  tags:
    - tmux

- name: Ranger-Konfiguration verteilen
  ansible.builtin.copy:
    src: "{{ common_dotfiles_path }}/.config/ranger"
    dest: "{{ item.home }}/.config/"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: '0755'
  loop: "{{ common_user_list }}"
  tags:
    - ranger

- name: .gitconfig einrichten
  ansible.builtin.copy:
    src: "{{ common_dotfiles_path }}/.gitconfig"
    dest: "/home/{{ common_user_main }}/.gitconfig"
    owner: "{{ common_user_main }}"
    group: "{{ common_user_main }}"
    mode: '0644'
  tags:
    - gitconfig

- name: Konfigurationsblock an die /root/.bashrc anhängen
  ansible.builtin.blockinfile:
    path: /root/.bashrc
    block: "{{ lookup('file', 'bashrc_custom.sh') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Custom bash settings"
    create: true
    owner: root
    group: root
    mode: '0644'
  tags:
    - bash

- name: .local/bin Verzeichnis für root anlegen
  ansible.builtin.file:
    path: /root/.local/bin
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - scripts

- name: Backup-Skript sraspi-backup für root verteilen
  ansible.builtin.copy:
    src: "{{ common_dotfiles_path }}/.local/bin/sraspi-backup"
    dest: /root/.local/bin/sraspi-backup
    owner: root
    group: root
    mode: '0755'
  tags:
    - scripts
