---
- name: Secrets laden
  ansible.builtin.include_vars: secrets.yml
  tags:
    - always

- name: Allgemeine Systemeinstellungen anwenden
  ansible.builtin.import_tasks: system.yml
  tags:
    - system

- name: Netzwerkeinstellungen konfigurieren
  ansible.builtin.import_tasks: network.yml
  tags:
    - network

- name: Speicher und Laufwerke einrichten
  ansible.builtin.import_tasks: storage.yml
  tags:
    - storage

- name: User anlegen
  ansible.builtin.import_tasks: user.yml
  tags:
    - user

- name: Persönliche Konfigurationen und Dotfiles verteilen
  ansible.builtin.import_tasks: dotfiles.yml
  tags:
    - dotfiles

- name: SSH-Sicherheit und Keys konfigurieren
  ansible.builtin.import_tasks: ssh.yml
  tags:
    - ssh
