---
# Liste der Standardpakete, die auf dem Server installiert werden sollen
apt_base_packages:
  - btrfs-progs
  - borgbackup

  - ca-certificates
  - curl
  - gnupg
  - wget
  - python3-debian

  - apache2-utils
  - certbot
  - bc

  - git
  - neovim
  - htop
  - ripgrep
  - tree
  - eza
  - ranger
