---
common_dotfiles_path: "~/Repositories/dotfiles"

common_network_country: "DE"

common_ssh_authorized_keys: >
  ssh-ed25519
  AAAAC3NzaC1lZDI1NTE5AAAAINENtXtotbI1gy4c8kYGBpzwDxCiN2cQmtRAETtZhZfj
  daniel.wujecki@gmail.com
common_ssh_user_pub: >
  ssh-ed25519
  AAAAC3NzaC1lZDI1NTE5AAAAIFzww/SNQ+E7nX0i9+Cv6MoTWTgSn62aZpqzzLVXeDg8
  raspberryserver.shilunski.de
common_ssh_root_pub: >
  ssh-ed25519
  AAAAC3NzaC1lZDI1NTE5AAAAIPPkM8/TG54Q7DwFzl/fGEe51DS9zvbs4DyvCzcMPoml
  root@raspberryserver

common_storage_partuuid: "c98333b3"

common_system_hostname: "raspberryserver"
common_system_timezone: "Europe/Berlin"
common_system_locale: "de_DE.UTF-8"

common_user_main: "daniel"
common_user_list:
  - { home: '/root', owner: 'root', group: 'root' }
  - { home: '/home/{{ common_user_main }}', owner: '{{ common_user_main }}', group: '{{ common_user_main }}' }
common_user_additional_groups:
  - adm
  - dialout
  - cdrom
  - sudo
  - audio
  - video
  - plugdev
  - games
  - users
  - input
  - render
  - netdev
  - spi
  - i2c
  - gpio
  - docker
