#!/bin/sh

xrandr --output default --mode 1920x1080 --dpi 96
xsetroot -solid \#292c42

OS_NAME=$(uname -n)
OS_INFO=$(uname -smr)
# xclock -digital -geometry -0+0 -strftime "$OS_NAME ($OS_INFO) | %a. %d %b. %Y  %H:%M " &

# $OpenBSD: Xsetup_0,v 1.8 2020/07/04 13:32:50 matthieu Exp $

# xsetroot -fg \#6f6f6f -bg \#bfbfbf -bitmap /usr/X11R6/include/X11/bitmaps/root_weave

# xconsole -geometry 480x130-0-0 -daemon -notify -verbose -fn fixed -exitOnFail

#  install package openbsd-backgrounds
#  then uncomment:
#
# if test -x /usr/local/bin/openbsd-wallpaper
# then
# 	/usr/local/bin/openbsd-wallpaper
# fi

# sxpm OpenBSD.xpm &
