#!/bin/bash
#  _
# | |__  ___ _ ____      ___ __ ___
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \
# | |_) \__ \ |_) \ V  V /| | | | | |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#           |_|
######################################

LAPTOP=
if [[ -f /etc/hostname ]] && grep -q 'ArchX1' /etc/hostname ; then
    LAPTOP=1
elif [[ -f /etc/conf.d/hostname ]] && grep -q 'ArchX1' /etc/conf.d/hostname ; then
    LAPTOP=1
fi

########################################################
# Xorg settings
########################################################

# general xorg settings
xsetroot -cursor_name left_ptr
xset dpms 600 600 600

xran="$(xrandr -q)"

if [[ $LAPTOP ]] ; then

    dp21="$(echo "$xran" | grep -- 'DP2-1 connected')"
    dp23="$(echo "$xran" | grep -- 'DP2-3 connected')"
    if [[ -n $dp21 && -n $dp23 ]] ; then
        xrandr --output eDP1 --off --output DP1 --off --output DP2 --off \
            --output DP2-2 --off --output DP2-1 --mode 2560x1440 --pos 0x0 --rotate normal --dpi 128 \
            --output DP2-3 --off --output HDMI1 --off --output VIRTUAL1 --off
        xrandr --output eDP1 --off --output DP1 --off --output DP2 --off \
            --output DP2-2 --off --output DP2-1 --mode 2560x1440 --pos 0x0 --rotate normal --dpi 128 \
            --output DP2-3 --primary --mode 2560x1440 --pos 2560x0 --rotate normal --dpi 128 \
            --output HDMI1 --off --output VIRTUAL1 --off
        bspc monitor "DP2-1" -d 0 1
        bspc monitor "DP2-3" -d 2 3 4 5 6 7 8 9
    else
        xrandr --output eDP1 --primary --mode 2560x1440 --pos 0x0 --rotate normal \
            --output DP1 --off --output DP2 --off \
            --output DP2-1 --off --output DP2-2 --off \
            --output DP2-3 --off --output HDMI1 --off \
            --output VIRTUAL1 --off
        bspc monitor -d 0 1 2 3 4 5 6 7 8 9
    fi

else

    dp0="$(echo "$xran" | grep -- 'DP-0 connected')"
    dp2="$(echo "$xran" | grep -- 'DP-2 connected')"
    if [[ -n $dp0 && -n $dp2 ]] ; then
        bspc monitor "DP-2" -d 0 1
        bspc monitor "DP-0" -d 2 3 4 5 6 7 8 9
    else
        bspc monitor -d 0 1 2 3 4 5 6 7 8 9
    fi

fi

########################################################
# BSPWM settings
########################################################

# bspwm specific settings
bspc config normal_border_color       "#2b2928"
bspc config active_border_color       "#3b3938"
bspc config focused_border_color      "#4b4948"
bspc config presel_feedback_color     "#5b5958"

#bspc config automatic_scheme          spiral
bspc config automatic_scheme          longest_side

bspc config border_width              3
bspc config split_ratio               0.5
bspc config window_gap                0

bspc config borderless_monocle        false
bspc config gapless_monocle           true
bspc config single_monocle            true
bspc config pointer_follows_monitor   true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

bspc config pointer_modifier          "mod4"

# bspwm rules
bspc rule -a Emacs state=tiled

#### example rules ####
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

########################################################
# Autostart
########################################################

# start background programs
"$HOME"/.local/bin/fehbg &
"$HOME"/.local/bin/launch-polybar &
"$HOME"/.local/bin/checkupdates_custom &
pgrep -u "$LOGNAME" -x sxhkd > /dev/null || sxhkd &
pgrep -u "$LOGNAME" -x picom > /dev/null || picom &
pgrep -u "$LOGNAME" -x lxpolkit > /dev/null || lxpolkit &
pgrep -u "$LOGNAME" -x birdtray > /dev/null || birdtray &
pgrep -u "$LOGNAME" -x nm-applet > /dev/null || nm-applet &
pgrep -u "$LOGNAME" -x emacs > /dev/null || emacs --daemon &
pgrep -u "$LOGNAME" -x dunst > /dev/null || dunst &
pgrep -u "$LOGNAME" -x redshift-gtk > /dev/null || redshift-gtk &
if [[ $LAPTOP ]] ; then
    pgrep -u "$LOGNAME" -x blueman-applet > /dev/null || blueman-applet &
fi
pgrep -u "$LOGNAME" -x element-desktop > /dev/null || element-desktop --hidden &
pgrep -u "$LOGNAME" -x telegram-desktop > /dev/null || telegram-desktop -startintray &
pgrep -u "$LOGNAME" -x xautolock > /dev/null || xautolock -detectsleep -time 10 -locker "betterlockscreen -l dimblur" &

bspc desktop -f 1
