#!/bin/bash
#  _
# | |__  ___ _ ____      ___ __ ___
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \
# | |_) \__ \ |_) \ V  V /| | | | | |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#           |_|
######################################

# general xorg settings
xsetroot -cursor_name left_ptr
xset dpms 600 600 600

xran="$(xrandr -q)"
dp22="$(echo "$xran" | grep -- 'DP2-2 connected')"
dp23="$(echo "$xran" | grep -- 'DP2-3 connected')"
if [[ -n $dp22 && -n $dp23 ]] ; then
    xrandr --output eDP1 --off --output DP1 --off --output DP2 --off \
        --output DP2-1 --off --output DP2-2 --mode 2560x1440 --pos 0x0 --rotate normal --dpi 128 \
        --output DP2-3 --off --output HDMI1 --off --output VIRTUAL1 --off
    xrandr --output eDP1 --off --output DP1 --off --output DP2 --off \
        --output DP2-1 --off --output DP2-2 --mode 2560x1440 --pos 0x0 --rotate normal --dpi 128 \
        --output DP2-3 --primary --mode 2560x1440 --pos 2560x0 --rotate normal --dpi 128 \
        --output HDMI1 --off --output VIRTUAL1 --off
    bspc monitor "DP2-2" -d 0 1
    bspc monitor "DP2-3" -d 2 3 4 5 6 7 8 9
    bspc desktop -f 1
    bspc desktop -f 2
else
    xrandr --output eDP1 --primary --mode 2560x1440 --pos 0x0 --rotate normal \
        --output DP1 --off --output DP2 --off \
        --output DP2-1 --off --output DP2-2 --off \
        --output DP2-3 --off --output HDMI1 --off \
        --output VIRTUAL1 --off
    bspc monitor -d 0 1 2 3 4 5 6 7 8 9
    bspc desktop -f 1
fi

# bspwm specific settings
bspc config normal_border_color       "#2b2928"
bspc config active_border_color       "#3b3938"
bspc config focused_border_color      "#4b4948"
bspc config presel_feedback_color     "#5b5958"

#bspc config automatic_scheme          spiral
bspc config automatic_scheme          longest_side

bspc config border_width              3
bspc config window_gap                12
bspc config split_ratio               0.5

bspc config borderless_monocle        false
bspc config gapless_monocle           true
bspc config single_monocle            true
bspc config pointer_follows_monitor   true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

bspc config pointer_modifier          "mod4"

# bspwm rules
bspc rule -a Emacs state=tiled

#### example rules ####
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# start programs
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x lxpolkit > /dev/null || lxpolkit &
pgrep -x nm-applet > /dev/null || nm-applet &
#pgrep -x emacs > /dev/null || emacs --daemon &
pgrep -u daniel -x dunst > /dev/null || dunst &
pgrep -x redshift-gtk > /dev/null || redshift-gtk &
pgrep -x blueman-applet > /dev/null || blueman-applet &
pgrep -x xautolock > /dev/null || xautolock -detectsleep -time 10 -locker "betterlockscreen -l dimblur" &
"$HOME"/.local/bin/fehbg &
"$HOME"/.local/bin/polybar_normal > /dev/null &
"$HOME"/.config/polybar/check_updates.sh > /dev/null &
