#!/bin/bash

# start programs
sxhkd &
picom -b > /dev/null 2>&1 &
nm-applet -b > /dev/null 2>&1 &
$HOME/.config/polybar/start_polybar_normal.sh > /dev/null 2>&1 &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           10

# colors
# bspc config normal_border_color "#1f2430"
# bspc config active_border_color "#1f2430"
# bspc config focused_border_color "#282f3e"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config automatic_scheme     spiral

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
