---
- name: Raspberry Pi Setup
  hosts: raspberryserver
  gather_facts: false
  become: true
  module_defaults:
    ansible.builtin.apt:
      cache_valid_time: 3600
    ansible.builtin.lineinfile:
      backup: true
    ansible.builtin.template:
      backup: true
    ansible.builtin.copy:
      backup: true

  roles:
    - role: apt
    - role: common
  #   - role: system      # Mounts WICHTIG! Vor Docker
  #   - role: hardware    # Lüfter
  #   - role: docker      # Installiert Docker (in die gemounteten Pfade)
  #   - role: webserver   # Nginx Ordner & Logrotate
