---
- name: Raspberry Pi Setup
  hosts: raspberryserver
  gather_facts: true
  become: true
  module_defaults:
    ansible.builtin.apt:
      cache_valid_time: 3600
    ansible.builtin.lineinfile:
      backup: true
    ansible.builtin.template:
      backup: true
    ansible.builtin.copy:
      backup: true

  roles:
    - role: apt
      tags: apt
    - role: common
      tags: common
    - role: docker
      tags: docker
