---
- name: Raspberry Pi Setup
  hosts: raspberryserver
  gather_facts: true
  become: true
  module_defaults:
    ansible.builtin.apt:
      cache_valid_time: 3600
    ansible.builtin.lineinfile:
      backup: true
    ansible.builtin.template:
      backup: true
    ansible.builtin.copy:
      backup: true

  roles:
    - role: apt
      tags: apt
    - role: common
      tags: common
    - role: docker
      tags: docker
    - role: shilunski_de
      tags: shilunski_de
      vars:
        shilunski_de_nginx: "1.31"
        shilunski_de_postgres: "17.10"
        shilunski_de_keycloak: "26.6"
        shilunski_de_mealie: "v3.20.1"
