---
- name: Apt-Cache aktualisieren
  ansible.builtin.apt:
    update_cache: true
  tags:
    - update
    - apt_upgrade

- name: System-Pakete upgraden
  ansible.builtin.apt:
    upgrade: true
  register: apt_upgrade_result
  notify: Server neu starten
  tags:
    - update
    - apt_upgrade

- name: Benötigte Pakete installieren
  ansible.builtin.apt:
    name: "{{ apt_base_packages }}"
    state: present
  tags:
    - apt_install

- name: Nicht mehr benötigte Abhängigkeiten entfernen (autoremove)
  ansible.builtin.apt:
    autoremove: true
  tags:
    - update
    - apt_upgrade

- name: Apt-Cache leeren (clean)
  ansible.builtin.apt:
    clean: true
  tags:
    - update
    - apt_upgrade

- name: Prüfen, ob ein System-Neustart erforderlich ist
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: apt_reboot_required_file
  changed_when: apt_reboot_required_file.stat.exists
  notify: Server neu starten
  tags:
    - never
    - update
    - apt_upgrade
